Fix order sensitivity of sensor computation.
moralmunky/Home-Assistant-Mail-And-Packages pull request #327
Opened 2021-01-08 04:37 UTC by blueshiftlabs

## Proposed change

The update() method of the sensor iterates through sensors in the order
they appear in the _resources list. Some sensors, such as the
*_delivering and zpackages_* sensors, depend on the values of earlier
sensors to compute their value. If the _resources list is not in exactly
the right order, this causes these sensors to show the wrong value.
Performing setup through the UI does not sort this list, and can cause
the summary sensors (zpackages_*) to break.

To fix this issue, abstract the "fetch one sensor" logic into a fetch()
method. That method can recursively call itself to fetch the value of
any of its dependencies. The values are cached, so that a given sensor
will only be computed once per update() pass, regardless of how many
times that sensor is fetch()ed.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

2021-01-08 04:40 UTC, blueshiftlabs commented
@firstof9 Looks like you're the one doing most of the reviews in this repo, please take a look.

2021-01-09 05:46 UTC, firstof9 commented
Sorry for the late updates, this didn't pop into my notifications for some reason.
I'd like to test this against the 0.3.0 branch as well and see how the tests run over it before merging and release.

Thank you for the contribution.

2021-01-09 18:53 UTC, firstof9 requested changes
Please bump the version in const.py to 0.2.3 as well.

2021-01-09 18:53 UTC, firstof9 commented on custom_components/mail_and_packages/sensor.py
> +            self._data = data
Updating `_data` twice

2021-01-10 04:33 UTC, firstof9 requested changes

2021-01-10 04:33 UTC, firstof9 commented on custom_components/mail_and_packages/sensor.py
>              self._data = data
This is the 2nd update

2021-01-10 16:25 UTC, firstof9 approved these changes

2021-01-10 16:27 UTC, merged