Update const.py
moralmunky/Home-Assistant-Mail-And-Packages pull request #876
Opened 2024-02-13 16:12 UTC by vinnie1234

## Breaking change
None

## Proposed change
Add extra email and subjects for PostNL

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation update
- [ ] Adds a new shipper
- [X] Update existing shipper

## Additional information
None

2024-02-13 19:14 UTC, firstof9 requested changes
Please format using `black` thanks!

2024-02-13 19:18 UTC, vinnie1234 commented
Ignore my last request please!

2024-02-14 07:52 UTC, vinnie1234 commented
I just added a new commit where I reformat the file with black

2024-02-14 13:41 UTC, firstof9 approved these changes

2024-02-14 13:41 UTC, merged