Added Walmart Delivering Sensor. Added new Subject to Walmart Delivered.
moralmunky/Home-Assistant-Mail-And-Packages pull request #884
Opened 2024-04-03 19:49 UTC by skewll

Added Walmart Delivering Sensor

Updated Walmart Delivered Sensor subject array.
Updated Walmart Delivered tracking pattern.

## Proposed change

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation update
- [ ] Adds a new shipper
- [x] Update existing shipper

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

2024-04-03 21:06 UTC, firstof9 requested changes

2024-04-03 21:06 UTC, firstof9 commented on custom_components/mail_and_packages/const.py
> +VERSION = "0.3.23"
```suggestion
VERSION = "0.0.0-dev"  # Now updated by release workflow
```
This get's updated when we do a release no need to adjust this.

2024-04-03 21:12 UTC, firstof9 commented
Just the recommendation and then formatting with black should check all the boxes :+1:

2024-04-04 01:46 UTC, skewll commented
I didn't change the version at all. I'm not sure how that happened. I've pushed a new commit with the suggested version change. I also used Microsoft's black extension. I hope that's the right extension.

2024-04-04 05:10 UTC, firstof9 approved these changes
Looks good, pending tests.

2024-04-04 13:23 UTC, firstof9 commented
Thanks!

2024-04-04 13:23 UTC, merged