Some more buildinglink subject lines
moralmunky/Home-Assistant-Mail-And-Packages pull request #938
Opened 2024-07-06 16:09 UTC by raccettura

Encountered a few more that I missed the first time around.  Mostly last-mile providers used by aliexpress and the like. The last one seems like a catch-all for anything not specifically in the system.

2024-07-06 22:45 UTC, firstof9 requested changes

2024-07-06 22:45 UTC, firstof9 commented on custom_components/mail_and_packages/const.py
>              "Your USPS delivery has arrived",
Can we try condensing lines 594-599 to:
```python
            "delivery has arrived",
```

2024-07-07 02:31 UTC, raccettura commented on custom_components/mail_and_packages/const.py
>              "Your USPS delivery has arrived",
Sounds reasonable to me.

2024-07-07 16:48 UTC, firstof9 approved these changes
Excellent, thanks!

2024-07-07 16:48 UTC, merged